/**
 * @file mock.ts
 * @description 留言板模块 mock 数据
 * @author TixXin
 * @since 2026-03-20
 */

import type { ActiveMember, ChatRule, ChatStat, DateGroup } from './types'

const ownerAvatar =
  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&q=80'

const avatars = {
  xiaoming: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?auto=format&fit=crop&w=80&q=80',
  xiaoli: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=80&q=80',
  ajie: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=80&q=80',
  dashu: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=80&q=80',
  css: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=80&q=80',
  xiaoyu: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&q=80',
  luna: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=80&q=80',
  codemaster: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&q=80',
  xiaohei: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&q=80',
  miko: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&q=80',
  zhangwei: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=80&q=80',
  lemon: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&q=80',
  devops: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=80&q=80',
}

export const mockDateGroups: DateGroup[] = [
  {
    date: '2024年3月18日',
    messages: [
      {
        id: 1,
        author: '开心果_小明',
        avatar: avatars.xiaoming,
        content: '第一次来到这个博客，界面太好看了吧！暗色模式下阅读很舒服，已经收藏了。',
        time: '03-18 09:23',
        isOwner: false,
        browser: 'Chrome 120',
        region: '广东广州',
      },
      {
        id: 2,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '欢迎欢迎！感谢认可，后续会持续更新实用内容。',
        time: '03-18 10:05',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 3,
        author: '前端小李',
        avatar: avatars.xiaoli,
        content: 'Vue3 响应式那篇文章写得真好，配合源码分析一看就懂，比啃文档轻松多了。',
        time: '03-18 14:18',
        isOwner: false,
        browser: 'Chrome 121',
        region: '北京',
      },
      {
        id: 4,
        author: '摄影爱好者阿杰',
        avatar: avatars.ajie,
        content: '画廊里的照片色调很高级，请问主要用什么相机？后期是 Lightroom 吗？',
        time: '03-18 20:31',
        isOwner: false,
        browser: 'Firefox 121',
        region: '上海',
      },
      {
        id: 5,
        author: 'Miko',
        avatar: avatars.miko,
        content: '留言板的聊天气泡设计好可爱！请问是用什么 UI 框架做的？',
        time: '03-18 21:45',
        isOwner: false,
        browser: 'Safari 17.3',
        region: '台湾台北',
      },
    ],
  },
  {
    date: '2024年3月19日',
    messages: [
      {
        id: 6,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '谢谢喜欢！主力是富士 X-T4，直出色彩就不错；后期偶尔用 Lightroom 微调。',
        time: '03-19 09:10',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 7,
        author: '后端大叔',
        avatar: avatars.dashu,
        content: '虽然平时写 Java，但每次来都能学到前端新东西，Tailwind 那篇让我对 CSS 有了新的认识。',
        time: '03-19 11:42',
        isOwner: false,
        browser: 'Chrome 120',
        region: '四川成都',
      },
      {
        id: 8,
        author: 'CSS魔法师',
        avatar: avatars.css,
        content: '首页 GitHub 风格热力图的实现很巧妙，用纯 JS 生成的吗？结构很清晰，学习了。',
        time: '03-19 15:07',
        isOwner: false,
        browser: 'Safari 17.2',
        region: '江苏南京',
      },
      {
        id: 9,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '@Miko 没有用框架，纯手写的 Vue 组件 + SCSS，有空可以看看源码~',
        time: '03-19 16:20',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 10,
        author: '张伟_DevOps',
        avatar: avatars.zhangwei,
        content: 'Docker 部署那篇太实用了，照着做一次就跑通了，省了半天排查时间。',
        time: '03-19 18:30',
        isOwner: false,
        browser: 'Chrome 121',
        region: '山东济南',
      },
      {
        id: 11,
        author: '小鱼儿',
        avatar: avatars.xiaoyu,
        content: '博主更新频率好高！请问是全职博主吗？每篇质量都很高诶。',
        time: '03-19 20:15',
        isOwner: false,
        browser: 'Chrome 120',
        region: '湖北武汉',
      },
    ],
  },
  {
    date: '2024年3月20日',
    messages: [
      {
        id: 12,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '不是全职哈，白天上班晚上写博客，周末集中整理。主要靠热爱驱动 :)',
        time: '03-20 08:30',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 13,
        author: 'Luna',
        avatar: avatars.luna,
        content: '友链页做得好精致，已经提交申请了，希望能通过！我的博客主要写设计相关内容。',
        time: '03-20 10:12',
        isOwner: false,
        browser: 'Chrome 121',
        region: '广东深圳',
      },
      {
        id: 14,
        author: 'CodeMaster_张',
        avatar: avatars.codemaster,
        content: 'TypeScript 类型体操那篇看了三遍才完全理解，作者功底深厚。能出一个进阶系列吗？',
        time: '03-20 11:45',
        isOwner: false,
        browser: 'Firefox 122',
        region: '浙江杭州',
      },
      {
        id: 15,
        author: '技术小黑',
        avatar: avatars.xiaohei,
        content: '项目页的卡片交互效果很细腻，hover 时的微动画恰到好处，不喧宾夺主。',
        time: '03-20 14:20',
        isOwner: false,
        browser: 'Chrome 120',
        region: '北京',
      },
      {
        id: 16,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '@Luna 已通过，欢迎互链！@CodeMaster_张 TS 进阶系列在规划中了，敬请期待。',
        time: '03-20 15:00',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 17,
        author: 'Lemon',
        avatar: avatars.lemon,
        content: '关于我页的技能进度条好有趣！想请教一下响应式布局方面有什么推荐的学习路线吗？',
        time: '03-20 16:35',
        isOwner: false,
        browser: 'Safari 17.3',
        region: '福建厦门',
      },
      {
        id: 18,
        author: '摄影爱好者阿杰',
        avatar: avatars.ajie,
        content: '富士直出确实好看！最近也入了 X-S20，有空一起交流摄影心得。',
        time: '03-20 19:10',
        isOwner: false,
        browser: 'Firefox 121',
        region: '上海',
      },
    ],
  },
  {
    date: '2024年3月21日',
    messages: [
      {
        id: 19,
        author: '前端小李',
        avatar: avatars.xiaoli,
        content: 'Nuxt 4 迁移指南写了吗？从 Nuxt 3 升级遇到了一些坑，希望博主能出一篇。',
        time: '03-21 09:00',
        isOwner: false,
        browser: 'Chrome 121',
        region: '北京',
      },
      {
        id: 20,
        author: 'DevOps老王',
        avatar: avatars.devops,
        content: '博客的加载速度很快，用了 CDN 还是边缘计算？Lighthouse 跑分多少？',
        time: '03-21 10:30',
        isOwner: false,
        browser: 'Chrome 122',
        region: '上海',
      },
      {
        id: 21,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '用的 Vercel Edge + Cloudflare CDN，Lighthouse 性能分大概 95+。Nuxt 4 迁移文章在写了！',
        time: '03-21 11:15',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 22,
        author: 'Miko',
        avatar: avatars.miko,
        content: '看了源码，原来气泡用的 flex + border-radius 实现，学到了！准备在自己项目里借鉴一下。',
        time: '03-21 13:40',
        isOwner: false,
        browser: 'Safari 17.3',
        region: '台湾台北',
      },
      {
        id: 23,
        author: '后端大叔',
        avatar: avatars.dashu,
        content: '能不能出一个 Node.js + Nuxt 全栈实战系列？从前到后完整走一遍那种。',
        time: '03-21 15:50',
        isOwner: false,
        browser: 'Chrome 120',
        region: '四川成都',
      },
      {
        id: 24,
        author: 'CSS魔法师',
        avatar: avatars.css,
        content: '深色主题下的颜色层次处理得很好，不是简单的反色，能看出花了心思调配。',
        time: '03-21 17:20',
        isOwner: false,
        browser: 'Safari 17.2',
        region: '江苏南京',
      },
      {
        id: 25,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '全栈系列是个好想法！先把 Nuxt 4 迁移写完，后面可以安排。暗色主题调了很久，谢谢认可！',
        time: '03-21 18:00',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
    ],
  },
  {
    date: '2024年3月22日',
    messages: [
      {
        id: 26,
        author: '张伟_DevOps',
        avatar: avatars.zhangwei,
        content: 'CI/CD 流水线那篇文章里的 GitHub Actions 配置，直接复制到项目里就能用，太方便了。',
        time: '03-22 09:30',
        isOwner: false,
        browser: 'Chrome 121',
        region: '山东济南',
      },
      {
        id: 27,
        author: 'Luna',
        avatar: avatars.luna,
        content: '互链成功了！顺便说一下，画廊里的城市夜景那张特别有氛围感，是在外滩拍的吗？',
        time: '03-22 11:00',
        isOwner: false,
        browser: 'Chrome 121',
        region: '广东深圳',
      },
      {
        id: 28,
        author: 'Lemon',
        avatar: avatars.lemon,
        content: '今天试了博主推荐的 CSS Grid 布局方案，效果真不错，再也不用 float 了哈哈。',
        time: '03-22 14:15',
        isOwner: false,
        browser: 'Safari 17.3',
        region: '福建厦门',
      },
      {
        id: 29,
        author: 'CodeMaster_张',
        avatar: avatars.codemaster,
        content: '发现一个小问题：文章详情页在 Safari 下目录定位偶尔不准，可能是 Intersection Observer 兼容性。',
        time: '03-22 16:40',
        isOwner: false,
        browser: 'Firefox 122',
        region: '浙江杭州',
      },
      {
        id: 30,
        author: 'TixXin',
        avatar: ownerAvatar,
        content: '@Luna 对，在陆家嘴拍的！@CodeMaster_张 感谢反馈，我排查一下 Safari 的兼容问题。',
        time: '03-22 17:30',
        isOwner: true,
        browser: 'Edge 120',
        region: '浙江杭州',
      },
      {
        id: 31,
        author: '小鱼儿',
        avatar: avatars.xiaoyu,
        content: '等不及看 Nuxt 4 迁移指南了！我也在准备升级，希望能避开一些常见的坑。',
        time: '03-22 19:55',
        isOwner: false,
        browser: 'Chrome 120',
        region: '湖北武汉',
      },
      {
        id: 32,
        author: '技术小黑',
        avatar: avatars.xiaohei,
        content: '请问博客的搜索功能后续会接入全文检索吗？现在只是前端过滤，数据量大了可能不够用。',
        time: '03-22 21:10',
        isOwner: false,
        browser: 'Chrome 120',
        region: '北京',
      },
    ],
  },
]

export const mockChatStats: ChatStat[] = [
  { label: '总留言', value: '1,234' },
  { label: '活跃用户', value: '89' },
  { label: '今日新增', value: '12' },
]

export const mockChatRules: ChatRule[] = [
  { id: 1, text: '请保持友善与尊重，避免人身攻击与挑衅言论。' },
  { id: 2, text: '欢迎技术讨论与不同观点，用事实与逻辑交流。' },
  { id: 3, text: '请勿发布广告、拉群、引流等与本站无关的推广信息。' },
  { id: 4, text: '涉及隐私、违法或不当内容将被删除，情节严重将拉黑处理。' },
]

export const mockActiveMembers: ActiveMember[] = [
  {
    name: 'TixXin',
    avatar: ownerAvatar,
    messageCount: 42,
  },
  {
    name: '小鱼儿',
    avatar: avatars.xiaoyu,
    messageCount: 18,
  },
  {
    name: 'Luna',
    avatar: avatars.luna,
    messageCount: 15,
  },
  {
    name: 'CodeMaster_张',
    avatar: avatars.codemaster,
    messageCount: 12,
  },
  {
    name: '前端小李',
    avatar: avatars.xiaoli,
    messageCount: 10,
  },
  {
    name: 'CSS魔法师',
    avatar: avatars.css,
    messageCount: 9,
  },
  {
    name: '摄影爱好者阿杰',
    avatar: avatars.ajie,
    messageCount: 8,
  },
  {
    name: 'Miko',
    avatar: avatars.miko,
    messageCount: 7,
  },
]
